### PR TITLE
Added Colour To Sell Signs

### PR DESCRIPTION
**Pull request by Bamuel**
they can be configure able

### CODE REVIEW

**Comment by ChalkPE** [comment]
Hey, color formats are only applied for one-line! (It means resetting them on next line is unneeded!)

**Comment by Bamuel** [comment]
"§l$§r%1"
is
$ makes the $ sign bold but returns the text to normal and outputs a normal number
so

Example
**$**200

**Comment by ChalkPE** [comment]
What I meant was "Amount : **§r**§l%3" on line 81!

**Comment by Bamuel** [comment]
lol made an accident

**Comment by ChalkPE** [comment]
Good :)

**Pull request merged**
