### PR TITLE
Compatibility with 1.6

### PR DESCRIPTION
**Pull request by Gamecrafter**
This PR fixes most if not all compatibility issues with PocketMine Alpha 1.6, by changing `Item::isPlaceable()` to `Item::canBePlaced()`.

### CODE REVIEW

**Comment by Pub4Game** [comment]
omg it's already fixed

**Comment by Gamecrafter** [comment]
@Pub4Game No, it isn't. Look through the code. :stuck_out_tongue:

**Comment by Pub4Game** [comment]
@Gamecrafter See https://github.com/onebone/EconomyS/commit/09a49eed9f197d1b84acbbebf75709d954f1154e

**Comment by Gamecrafter** [comment]
@Pub4Game :o I keep forgetting to look in other branches.

**Pull request closed without merging**
