### PR TITLE
SQL work

### PR DESCRIPTION
**Pull request by jasonwynn10**
Only push these commits when they are done!

### CODE REVIEW

**Comment by Driesboy** [comment]
Nice

**Comment by jasonwynn10** [comment]
Can someone test this on their server? I won't be able to test it for another week

**Comment by ZINGDING** [comment]
Awesome~!

**Comment by onebone** [comment]
It would be nice to get these things fixed:

1. Indenting. Use tabs properly to improve readability. (Not spaces)
2. EconomyAPI uses a decimal point for money to support cents.
3. Remove potential risk of SQL injection by escaping username.

**Comment by jasonwynn10** [comment]
got it! I will work on it some more then 👍

**Comment by jasonwynn10** [comment]
anything else needed @onebone ?

**Comment by onebone** [comment]
Please escape for SQLite3 because it also uses SQL. And indenting :D

**Comment by jasonwynn10** [comment]
There isn't a function for that in sqlite3. You might be thinking of the one in sqlite

**Comment by jasonwynn10** [comment]
I finished the formatting, but there isn't a function to escape the string for sqlite3

**Comment by jasonwynn10** [comment]
Everything is done as you asked @onebone 
I think it's ready to merge. :smile:

**Comment by onebone** [comment]
Have you tested MySQL? I have tested now, and failed to create table.

**Comment by jasonwynn10** [comment]
yikes! :worried: 
I'll start work on a fix... :disappointed:

**Comment by linuzo** [comment]
So is MySQL working now?

**Pull request closed without merging**
