### PR TITLE
Dog194 patch reorder some message

### PR DESCRIPTION
**Pull request by dog194**
reorder some message

### CODE REVIEW

**Comment by dog194** [comment]
@onebone OK this request do not have a conflict.

**Comment by dog194** [comment]
Ｏ(≧口≦)Ｏ  Sorry！！！ the commit "Update for preparing" is wrong. I add it into a wrong brance. So wait me for changing.

**Comment by dog194** [comment]
OK I have reverted this commit

**Comment by dog194** [comment]
OK I have reverted this commit

**Comment by dog194** [comment]
@onebone

**Comment by onebone** [comment]
:+1:

**Pull request merged**
