### PR TITLE
Dog194 patch EconomyLand notp

### PR DESCRIPTION
**Pull request by dog194**
Allow land owner to disallow others to use "/land move" to tp to their land.(except op and invitee)

### CODE REVIEW

**Comment by dog194** [comment]
enhancement for  #217

**Comment by dog194** [comment]
oh. @onebone

**Comment by onebone** [comment]
@dog194 I will review it later.

**Comment by dog194** [comment]
oh....@onebone I creat this pull request alomost two months ago. At that time there is no a conflicts. But now ..... Would you mind spending some time having a look. And give me a response. If yes i will re-create a new pull request, If no Plz just close it.

**Comment by dog194** [comment]
fine. It is time to close this.

**Pull request closed without merging**
