### PR TITLE
dutch 2.0

### PR DESCRIPTION
**Pull request by dries-c**
dutch

### CODE REVIEW

**Comment by ChalkPE** [comment]
It has a syntax error: you should use `"neutral quotation marks"` instead of `“these”`

**Comment by Driesboy** [comment]
how can i fix it

**Comment by dog194** [comment]
Look at this detail .  is    ”  "   no    “   ”

**Comment by dog194** [comment]
qq 20151114151449

**Comment by Driesboy** [comment]
Fix

**Comment by Driesboy** [comment]
its fixed

**Comment by Driesboy** [comment]
7 days or i will close this pull request

**Comment by dog194** [comment]
Just wait for ChalkPE  or Onebone to check

**Comment by Driesboy** [comment]
i wait 4 days ok

**Comment by dog194** [comment]
Yes 4 days. So? I wait 4 days too in another Pull request #205. If you are in hurry, you can just change the file into your sever first. Then just wait for checking and new eidition out.

**Comment by Driesboy** [comment]
i have update it to my server

**Comment by ChalkPE** [comment]
Oh, I'm sorry I'm late and thank you for your support!

**Comment by dog194** [comment]
well Driesboy, your pull request has been merged. But i  still need to wait for Onebone. :D

**Comment by Driesboy** [comment]
Ok

**Comment by JustTalDevelops** [comment]
I wait 3 days ok?

**Comment by sylvrs** [comment]
Thank for request ok!

**Comment by john-bv** [comment]
7 days, ok?

**Comment by TobiasGrether** [comment]
I have update it on my server

**Comment by john-bv** [comment]
working now it is?

**Comment by mat345st** [comment]
when comes the new dutch update? dutch 3.0?

**Comment by JellyBrick** [comment]
Please refrain from leaving comments that are not relevant to this pull request.

**Comment by T14Raptor** [comment]
Who the hell is JellyBrick?

**Comment by JustTalDevelops** [comment]
> Please refrain from leaving comments that are not relevant to this pull request.

random

**Pull request merged**
